POST http://localhost:8080/auth/register
Content-Type: application/json

{
	"name": "Rafael Áquila",
	"email": "ca@gmail.com",
	"password": "123456789",
	"confirmPassword": "123456789"
}

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
	"email": "Rafael@gmail.com",
	"password": "123456789"
}

###

GET http://localhost:8080/user/65dcf117f8b3243061eefef3